baseurl = "https://aaltomcc.github.io/cs-ej4101-fall-2019-047-advanced"
title = "Ahmed Massoud DevOps Project"

theme = "T1"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true



[params]
    author = "About"
    info = "Hi there!, I am creating this website for the final project for DevOps course, I am very glad that you are reading this right now!, I am studying internet technologies track in comnet Aalto University, my major focuses on computer network which includes routing, SDN, internet traffic measurements, internet protocols, that also including secuirty, But as we all know that software development skill is a very important skill right now, where everyone works in any digital field need, so I am currently improving my skills in computer science by having it as a minor in my degree and studying more courses about software development including web development using python and at the moment I am working on my skill using javascript frameworks nodejs and react, I also have some old knowledge about PHP :D pretty old ya :D, I am taking this course to learn about DevOps because before this course I did have no knowledge about the subject which is great."
    keywords = "blog,developer,personal" 
    description = ""
    avatarurl = "images/dev.webp"
    footercontent = "Dev Ops Project 047"




    hideCredits = true
    hideCopyright = false



    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "dark"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []
    
    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "About course"
    weight = 1
    url  = "posts/about-this-course"
[[params.social]]
    name = "About learning"
    weight = 2
    url  = "posts/about-learning"

[[menu.main]]
    name = "About course"
    weight = 1
    url  = "posts/about-this-course"
[[menu.main]]
    name = "About learning"
    weight = 2
    url  = "posts/about-learning"







